package com.haresh.leetcode.problems;

/*
    389. Find the Difference
    https://leetcode.com/problems/find-the-difference/

    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

    Example 2:
    Input: s = "", t = "y"
    Output: "y"

    Constraints:
        0 <= s.length <= 1000
        t.length == s.length + 1
        s and t consist of lowercase English letters.
 */

/**
 * @author Haresh Shaha
 * @since 07-Feb-2022
 */
public class Program145 {
    public static void main(String[] args) {
        String s = "abcd", t = "abcde";
        char missingChar = findTheDifference(s, t);
        System.out.println(missingChar);
    }

    public static char findTheDifference(String s, String t) {
        int[] charMap1 = new int[26];
        int[] charMap2 = new int[26];
        for (int i = 0; i < s.length(); i++) {
            charMap1[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < t.length(); i++) {
            charMap2[t.charAt(i) - 'a']++;
        }

        for (int i = 0; i < 26; i++) {
            if (charMap1[i] != charMap2[i]) {
                return (char) (i + 'a');
            }
        }
        return 'a';
    }
}
